### ISSUE TITLE
Attraction Details - when converting to german, the default text is not translating

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#10]
<img width="1383" alt="Screen Shot 2021-06-01 at 10 02 48 AM" src="https://user-images.githubusercontent.com/8318784/120274268-a6084000-c2c0-11eb-8060-ca28ba9644b5.png">

**Comment by melee1984** [comment]
just need to reset server cache

<img width="1430" alt="Screen Shot 2021-06-16 at 11 03 45 AM" src="https://user-images.githubusercontent.com/2749924/122151695-91b46d80-ce92-11eb-8da9-ad741e02eed0.png">
