### ISSUE TITLE
Attracting listing - check layout issue on german language

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#11]
![screencapture-dev-soporella-themepark-2021-06-01-10_05_18](https://user-images.githubusercontent.com/8318784/120274498-fc757e80-c2c0-11eb-9609-3bc7e2235e56.png)

**Comment by melee1984** [comment]
I have noticed that the description does content special character which suppose to be only plain text. updated the layout.

**Comment by melee1984** [comment]
<img width="1373" alt="Screen Shot 2021-06-16 at 12 22 55 PM" src="https://user-images.githubusercontent.com/2749924/122157550-9b8f9e00-ce9d-11eb-8667-cf02ee42eb86.png">
