### ISSUE TITLE
Subscribe to newsletter - layout issue on different

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#13]
<img width="1270" alt="Screen Shot 2021-06-01 at 10 10 19 AM" src="https://user-images.githubusercontent.com/8318784/120275007-ba990800-c2c1-11eb-8d30-5bfab4ddaee3.png">

**Comment by melee1984** [comment]
updated 
<img width="1218" alt="Screen Shot 2021-06-16 at 10 52 35 AM" src="https://user-images.githubusercontent.com/2749924/122150804-fd95d680-ce90-11eb-9d64-fa06bb8d7396.png">
