### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#14]
<img width="1426" alt="Screen Shot 2021-06-01 at 10 12 12 AM" src="https://user-images.githubusercontent.com/8318784/120275145-ed430080-c2c1-11eb-9d77-7d2edf331b0c.png">

maka search japun even wala syay gibutang na content sa search for attraction

**Comment by melee1984** [comment]
updated search values without attraction and will be filter based on the location or emirate value
