### ISSUE TITLE
Calendar default: Next booking is 5 days later prior to the purchase

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#2]
Calendar default: Next booking is 5 days later prior to the purchase

![image](https://user-images.githubusercontent.com/8318784/119444276-008f2280-bd3c-11eb-84ab-7e802fc6b73b.png)

**Comment by melee1984** [comment]
This was fixed. already uploaded it from the development. 
![Screen Shot 2021-05-26 at 8 06 02 AM](https://user-images.githubusercontent.com/2749924/119583515-5aa1ed80-bdf9-11eb-8d84-e4d09bacc6c1.png)
