### ISSUE TITLE
Translation for static labels for german language

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#35]
**Header Part**

1.	My Tickets to Meine Tickets
2.	Put the British flag and remove the German and French Flag when you are in the German Site 
3.	Same for the English Site, remove the US and French flag and keep only the German flag. 
4.     Replace Beforderungen (Promotion in US) with Angebote

**Attraction Page**

_1.	When are you going? Change to Besuchstag_
_2.	Ticket Type to Ticket_
_3.     Please replace Availability with Verfügbarkeit_
_4.  	Please replace Redemption with Einlösung_
_5.     Switch Ticket Details (label) and About (label ) Placement._

**Newsletter Section**

11.	Change Subscribe to our Newsletter with  _Abonnieren Sie unseren Newsletter_     and change the text underneeth the subscription field to     _In unserem periodisch erscheinenden Newsletter finden Sie tolle Angebote und Artikel über die neuesten Attraktionen.    Also please exchange the field Subscribe with Abonnieren_

**Footer**

1.	Please make Quick Link like Wir akzeptieren in 2 lines so it looks uniform
2.	Remove Verkaufen Sie Tickes mit uns
3.	Allgemeine Geschaeftsbedingungen is one subject. Please keep this in one line or underneath each other
4.	Replace Kontaktiere uns with Kontakt
5.	In the final part of the Footer please change                                                               Soporella - Ihre Verkaufsstelle für all Attraktionen in den Vereinigten Arabischen Emiraten. Alle Rechte vorbehalten. 2021. 
Teil von ostiarius OÜ

**Comment by melee1984** [comment]
adjusted please review the changes.. Thank you.
