### ISSUE TITLE
Rate Description Convert to Wysiwyg

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#4]
Convert Rate desc to wysiwyg
![image](https://user-images.githubusercontent.com/8318784/119603557-7d82d080-bdfe-11eb-8994-cad970c68543.png)

**Comment by melee1984** [comment]
uploaded chnage converted Description with Wysiwgg

**Comment by melee1984** [comment]
<img width="1218" alt="Screen Shot 2021-06-16 at 10 52 35 AM" src="https://user-images.githubusercontent.com/2749924/122151302-e73c4a80-ce91-11eb-942b-0bf83b2427b1.png">
