### ISSUE TITLE
Homepage Content - How to add german text for this.

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#7]
<img width="1309" alt="Screen Shot 2021-06-01 at 9 56 31 AM" src="https://user-images.githubusercontent.com/8318784/120273701-e87d4d00-c2bf-11eb-8135-ea9484195670.png">

**Comment by melee1984** [comment]
Updated the best safety standard getting content directly from the message text. 
<img width="1520" alt="Screen Shot 2021-06-16 at 11 08 54 AM" src="https://user-images.githubusercontent.com/2749924/122152090-50708d80-ce93-11eb-994f-6411c610a71d.png">
