### ISSUE TITLE
Icon Calendar in attraction is too small

### ISSUE THREAD

**Issue by Larzz** [melee1984/soporella.com#9]
<img width="1420" alt="Screen Shot 2021-06-01 at 10 00 25 AM" src="https://user-images.githubusercontent.com/8318784/120274095-6c373980-c2c0-11eb-9193-3e475d70936f.png">

**Comment by melee1984** [comment]
Updated icon size: 

![Uploading Screen Shot 2021-06-16 at 10.43.05 AM.png…]()
